"$schema" = "./node_modules/wrangler/config-schema.json"
name = "hoopslab-web"
pages_build_output_dir = ".vercel/output/static"
compatibility_date = "2026-02-25"
compatibility_flags = ["nodejs_compat"]
